### ISSUE TITLE
Undefined name 'xdoc' in ubelt/util_colors.py

### ISSUE THREAD

**Issue by cclauss** [Erotemic/ubelt#23]
flake8 testing of https://github.com/Erotemic/ubelt on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./ubelt/util_colors.py:107:5: F821 undefined name 'xdoc'
    xdoc.doctest_module()
    ^
1     F821 undefined name 'xdoc'
1
```

**Comment by Erotemic** [comment]
Thanks for raising the issue! This was a holdout from refactoring the old internal ubelt doctesting harness into the new [xdoctest](https://github.com/Erotemic/xdoctest) module. I just fixed it with a hotfix in the master branch.
