### ISSUE TITLE
Request: ensure director verbose mentions if it created a new directory

### ISSUE THREAD

**Issue by cfunk1210** [Erotemic/ubelt#54]
It would be nice if the verbose mode actually said something like 
Ensuring directory ('...') status: existing
Ensuring directory ('...') status: creating

Maybe have a second verbose level if you want to maintain the original way.

**Comment by Erotemic** [comment]
It actually does do this. 

If the directory doesn't exist it says: `print('Ensuring new directory ({!r})'.format(dpath))`. 

If the directory does exist it says: `print('Ensuring existing directory ({!r})'.format(dpath))`. 

but perhaps that's not clear. I'll change it to:

```python
            print('Ensuring directory (create {!r})'.format(dpath))
            print('Ensuring directory (exists {!r})'.format(dpath))
```

This is fixed by #64
